name = "zen-nautica"
compatibility_date = "2024-02-10"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
output_directory = "dist"

[site]
bucket = "dist"

[miniflare]
port = 8787
watch = true